name: Instagram Otomasyon

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  indir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Calistir
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          pip install requests google-api-python-client google-auth yt-dlp -q
          python indir.py
